classes:
  explorer:
    fall_reduction: 0.5
    dash:
      duration: 10 # in seconds
      cooldown: 30 # in seconds
      speed: 1 # amplifier (0 = Speed I, 1 = Speed II)
    hydration:
      hunger: 1
      saturation: 0.5
    jump_boost_lvl: 10
    water_breathing:
      duration: 15 # in seconds
      cooldown: 10 # in seconds
    recall:
      cooldown: 60 # in seconds
  miner:
    diet:
      hunger: 4
      saturation: 2
    sight_lvl: 30
    haste:
      duration: 15 # in seconds
      cooldown: 20 # in seconds
      amp: 1 # amplifier (0 = Haste I, 1 = Haste II)
  builder:
    feast:
      hunger: 2
      saturation: 0.8
    grace_lvl: 20
    grace:
      duration: 10 # in seconds
      cooldown: 45 # in seconds
      jump: 2 # amplifier
